### ISSUE TITLE
Substrate Count_Calcs

### ISSUE THREAD

**Issue by SCCWRP-IM** [SCCWRP/PHABMetrics#2]
For the PCT_CB, PCT_FN, PCT_GC, PCT_GF,  PCT_HP, PCT_OT, PCT_RC, PCT_RR, PCT_RS, PCT_SA, PCT_SB, PCT_WD, PCT_XB:

We had to count null values in order to make the result values of these metrics match the result from the old method of calculation.

Also we had to ignore the record where LocationCode was 'Reach"

**Comment by r7butler** [comment]
for the Station 404M07362 and sampledate 2017-06-08, it appears as if the legacy calculation in fact did exclude null values when getting the count_calc value. Only for that station though, as far as i can see.
