### ISSUE TITLE
example in flow help file fails

### ISSUE THREAD

**Issue by fawda123** [SCCWRP/PHABMetrics#21]
Returns an error about non-unique keys when trying to spread on this line:
https://github.com/SCCWRP/PHABMetrics/blob/d1d3e7c53578039d84677accd3838a0fac9d41a1/R/flow.R#L39

Possibly related to not adding `MethodName` in #18 ?

```r
flow(sampdat)
Error: Each row of output must be identified by a unique combination of keys.
Keys are shared for 480 rows:
* 115, 173, 235, 289, 347, 405, 512
* 112, 165, 238, 281, 339, 397, 514
* 121, 164, 228, 280, 338, 396, 490
* 110, 153, 240, 269, 327, 385, 496
* 107, 152, 237, 268, 326, 384, 495
* 99, 150, 222, 266, 324, 382, 479
* 122, 159, 217, 275, 333, 391, 483
* 105, 157, 225, 273, 331, 389, 499
* 119, 186, 215, 302, 360, 418, 489
* 127, 170, 232, 286, 344, 402, 487
* 98, 175, 224, 291, 349, 407, 505
* 129, 177, 210, 292, 351, 409, 492
* 94, 179, 230, 295, 353, 411, 501
* 102, 182, 211, 298, 356, 414, 481
* 124, 184, 213, 300, 358, 416, 485
* 93, 180, 219, 296, 354, 412, 506
* 114, 155, 207, 271, 329, 387, 508
* 104, 167, 244, 283, 341, 399, 476
* 91, 162, 243, 278, 336, 394, 503
* 61, 471
* 51, 455
* 47, 468
* 66, 458
* 69, 460
* 50, 465
* 56, 463
* 70, 462
* 53, 452
* 63, 472
* 65, 454
* 58, 475
* 116, 171, 233, 287, 345, 403, 511
* 111, 166, 239, 282, 340, 398, 513
* 120, 163, 227, 279
```

**Comment by r7butler** [comment]
I would say it is related to #18. The new code in flow expects methodname to be in there

**Comment by fawda123** [comment]
So we need to add `MethodName` to the sample data that comes with the package - we can just nix it and use some new sample data from the server since I don't remember where sampdat came from if that's easier.

**Comment by r7butler** [comment]
yea that might be easier. Me and Thi just ran metrics locally on three different data sets and they all ran. Paul has a set called "test.mdb" which we can turn into an excel, grab a few stations from that and then call it sampdat.

**Comment by fawda123** [comment]
Okay, just do that, I'll create a new issue
