### ISSUE TITLE
make new sampdat file

### ISSUE THREAD

**Issue by fawda123** [SCCWRP/PHABMetrics#22]
* include all fields, including `MethodName` and `SampleAgencyCode`
* limit to four sites

**Comment by fawda123** [comment]
Close #18 when this is done

**Comment by r7butler** [comment]
I put the new sampdat on my branch. Don't want to close it until it is merged to master and it has your approval.

**Comment by r7butler** [comment]
!!!!!!! AHH LOL I didn't mean to click close and comment.......

**Comment by fawda123** [comment]
11ba127e44f7a599192aa2f0025575038fda8954
